export const DEFAULT_CITY = process.env.NEXT_PUBLIC_DEFAULT_CITY || 'Delhi';
export const OPENWEATHER_BASE_URL = process.env.NEXT_PUBLIC_OPENWEATHER_BASE_URL;
export const OPENWEATHER_API_KEY = process.env.NEXT_PUBLIC_OPENWEATHER_API_KEY;
